/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CollateralToken__factory } from "./CollateralToken__factory";
export { LendingProtocol__factory } from "./LendingProtocol__factory";
export { LoanToken__factory } from "./LoanToken__factory";
