/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BorrowableAsset } from "./BorrowableAsset";
export type { CollateralAsset } from "./CollateralAsset";
export type { DeFiLending } from "./DeFiLending";
export type { TimeLock } from "./TimeLock";
