/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CollateralToken } from "./CollateralToken";
export type { LendingProtocol } from "./LendingProtocol";
export type { LoanToken } from "./LoanToken";
