/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  BigNumberish,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { PayableOverrides } from "../../common";
import type { TimeLock, TimeLockInterface } from "../../contracts/TimeLock";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_releaseTime",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "LockedRelease",
    type: "event",
  },
  {
    inputs: [],
    name: "beneficiary",
    outputs: [
      {
        internalType: "address payable",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "releaseTime",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405260405161028a38038061028a833981016040819052602091608b565b42811160725760405162461bcd60e51b815260206004820152601b60248201527f52656c656173652074696d65206d757374206265206675747572650000000000604482015260640160405180910390fd5b600055600180546001600160a01b0319163317905560a3565b600060208284031215609c57600080fd5b5051919050565b6101d8806100b26000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c806338af3eed146100465780633ccfd60b14610076578063b91d400114610080575b600080fd5b600154610059906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b61007e610097565b005b61008960005481565b60405190815260200161006d565b6000544210156100e15760405162461bcd60e51b815260206004820152601060248201526f139bdd081e595d081d5b9b1bd8dad95960821b60448201526064015b60405180910390fd5b6001546001600160a01b0316331461012a5760405162461bcd60e51b815260206004820152600c60248201526b155b985d5d1a1bdc9a5e995960a21b60448201526064016100d8565b6040805147808252426020830152917f67e810040328e183527c6f13781c7eabc4a70bab99f319d1dbb1840c29f1295f910160405180910390a16001546040516001600160a01b039091169082156108fc029083906000818181858888f1935050505015801561019e573d6000803e3d6000fd5b505056fea26469706673582212202fbe20173d9076e7fbb5e1670816621e0383f92215c62972b07d448e18f5e3c164736f6c634300081c0033";

type TimeLockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TimeLockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TimeLock__factory extends ContractFactory {
  constructor(...args: TimeLockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _releaseTime: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_releaseTime, overrides || {});
  }
  override deploy(
    _releaseTime: BigNumberish,
    overrides?: PayableOverrides & { from?: string }
  ) {
    return super.deploy(_releaseTime, overrides || {}) as Promise<
      TimeLock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TimeLock__factory {
    return super.connect(runner) as TimeLock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TimeLockInterface {
    return new Interface(_abi) as TimeLockInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): TimeLock {
    return new Contract(address, _abi, runner) as unknown as TimeLock;
  }
}
